spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always