spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081