version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/synapsex

hooks:

  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy.sh
      timeout: 500
      runas: root
